using DATMOS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DATMOS.Data
{
    public class ExamProjectSeeder
    {
        public static async Task SeedAsync(AppDbContext context)
        {
            // Check if there are already ExamProjects in the database
            if (await context.ExamProjects.AnyAsync())
            {
                Console.WriteLine("ExamProjects already seeded. Skipping...");
                return;
            }

            // Check if there are ExamLists in the database
            var examLists = await context.ExamLists.OrderBy(e => e.Id).ToListAsync();
            if (!examLists.Any())
            {
                Console.WriteLine("No ExamLists found. Please seed ExamLists first.");
                return;
            }

            Console.WriteLine($"Found {examLists.Count} ExamLists. Seeding 6 projects for each...");

            try
            {
                var examProjects = new List<ExamProject>();
                var projectCounter = 1;

                foreach (var exam in examLists)
                {
                    // Create 6 projects for each exam
                    for (int i = 1; i <= 6; i++)
                    {
                        var examProject = new ExamProject
                        {
                            // Id will be auto-generated by database
                            ExamListId = exam.Id,
                            Name = GetProjectName(exam.Id, i),
                            Description = GetProjectDescription(exam.Id, i),
                            TotalTasks = GetTotalTasks(i),
                            OrderIndex = i,
                            IsActive = true,
                            CreatedAt = DateTime.UtcNow
                        };

                        examProjects.Add(examProject);
                        projectCounter++;
                    }
                }

                // Add to database
                await context.ExamProjects.AddRangeAsync(examProjects);
                await context.SaveChangesAsync();

                Console.WriteLine($"Successfully seeded {examProjects.Count} ExamProjects for {examLists.Count} exams.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error seeding ExamProjects: {ex.Message}");
                throw;
            }
        }

        private static string GetProjectName(int examId, int projectNumber)
        {
            var examPrefix = examId switch
            {
                1 => "Word",
                2 => "Excel", 
                3 => "PowerPoint",
                _ => "Exam"
            };

            return $"{examPrefix} - Project {projectNumber}";
        }

        private static string GetProjectDescription(int examId, int projectNumber)
        {
            var skill = projectNumber switch
            {
                1 => "định dạng văn bản cơ bản",
                2 => "header/footer và SmartArt",
                3 => "bảng biểu và biểu đồ",
                4 => "mail merge và templates",
                5 => "collaboration và review",
                6 => "advanced formatting",
                _ => "bài tập thực hành"
            };

            return $"Bài tập thực hành {skill} cho {GetExamType(examId)}.";
        }

        private static string GetExamType(int examId)
        {
            return examId switch
            {
                1 => "Word 2019",
                2 => "Excel 2019",
                3 => "PowerPoint 2019",
                _ => "Office ứng dụng"
            };
        }

        private static int GetTotalTasks(int projectNumber)
        {
            // Vary tasks between 5-7 per project
            return 5 + (projectNumber % 3);
        }
    }
}
